import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import Decimal from 'decimal.js-light';
import { z } from 'zod';
import { environment } from '../environment';
import { LiveRatesChartComponent } from './live-rates/live-rates-chart.component';

type Lang='en'|'ru'|'uk'; type Theme='light'|'dark';
type Tx={type:'paid'|'pending'|'rejected';amount:string;currency:string};
type First={transactions:Tx[];address:{city:string;street:string;houseNumber:number}};
type Payment={amount:string;currency:string}; type Currencies={date:string;base:string;rates:Record<string,string>};
type Data={financeResult:[First,Payment[]];currencyData:Currencies};
type ErrorCode='invalidApiResponse'|'requestFailed'|'missingCurrencyApiKey'|'missingCurrencyRate'|'unknownError';
class AppError extends Error { constructor(readonly code:ErrorCode,readonly values:Record<string,string>={}){super(code)} }
const tr={
 en:{darkTheme:'Dark theme',lightTheme:'Light theme',language:'Language',formTitle:'Get financial data',formDescription:'Enter an access key to retrieve and combine data from financial sources.',apiKey:'API key',apiKeyPlaceholder:'Enter API key',apiKeyHelp:'The key is used only for this request and is not stored.',apiKeyRequired:'Enter an API key.',loading:'Loading data...',submit:'Send request',total:'Total amount',finalRounded:'The final value is bank-rounded in {currency}.',totalsByCurrency:'Amounts by currency',noIntermediateRounding:'No intermediate rounding',currentRates:'Current rates',asOf:'As of {date}',invalidApiResponse:'{source} returned data in an unknown format.',requestFailed:'{source} request failed (HTTP {status}).',missingCurrencyApiKey:'The currency API key is not configured.',missingCurrencyRate:'No exchange rate was provided for {currency}.',unknownError:'An unknown error occurred.'},
 ru:{darkTheme:'Тёмная тема',lightTheme:'Светлая тема',language:'Язык',formTitle:'Получение финансовых данных',formDescription:'Введите ключ доступа для получения и объединения данных из финансовых источников.',apiKey:'API-ключ',apiKeyPlaceholder:'Введите API-ключ',apiKeyHelp:'Ключ используется только для текущего запроса и не сохраняется.',apiKeyRequired:'Введите API-ключ.',loading:'Получение данных...',submit:'Отправить запрос',total:'Общая сумма',finalRounded:'Финальное значение округлено по банковскому правилу в {currency}.',totalsByCurrency:'Суммы по валютам',noIntermediateRounding:'Без промежуточного округления',currentRates:'Актуальные курсы',asOf:'По состоянию на {date}',invalidApiResponse:'{source}: API вернул данные неизвестного формата.',requestFailed:'{source}: ошибка запроса (HTTP {status}).',missingCurrencyApiKey:'Не настроен ключ валютного API.',missingCurrencyRate:'Для валюты {currency} не предоставлен курс обмена.',unknownError:'Произошла неизвестная ошибка.'},
 uk:{darkTheme:'Темна тема',lightTheme:'Світла тема',language:'Мова',formTitle:'Отримання фінансових даних',formDescription:'Введіть ключ доступу для отримання та об’єднання даних із фінансових джерел.',apiKey:'API-ключ',apiKeyPlaceholder:'Введіть API-ключ',apiKeyHelp:'Ключ використовується лише для поточного запиту та не зберігається.',apiKeyRequired:'Введіть API-ключ.',loading:'Отримання даних...',submit:'Надіслати запит',total:'Загальна сума',finalRounded:'Кінцеве значення округлено за банківським правилом у {currency}.',totalsByCurrency:'Суми за валютами',noIntermediateRounding:'Без проміжного округлення',currentRates:'Актуальні курси',asOf:'Станом на {date}',invalidApiResponse:'{source}: API повернув дані невідомого формату.',requestFailed:'{source}: помилка запиту (HTTP {status}).',missingCurrencyApiKey:'Не налаштовано ключ валютного API.',missingCurrencyRate:'Для валюти {currency} не надано курс обміну.',unknownError:'Сталася невідома помилка.'}
} as const; type Key=keyof typeof tr.en;
const code=z.string().trim().transform(v=>v.toUpperCase()).pipe(z.string().regex(/^[A-Z]{3}$/));
const money=z.union([z.string(),z.number().finite()]).transform(String).pipe(z.string().regex(/^-?\d+(?:\.\d+)?$/));
const firstSchema=z.object({transactions:z.array(z.object({type:z.enum(['paid','pending','rejected']),amount:money,currency:code})),address:z.object({city:z.string(),street:z.string(),houseNumber:z.number().finite()})});
const secondSchema=z.array(z.string()).transform((xs,ctx)=>xs.map(x=>{const m=x.trim().match(/^(-?\d+(?:\.\d+)?)\s+([A-Za-z]{3})$/);if(!m){ctx.addIssue({code:'custom',message:'Invalid payment'});return {amount:'0',currency:'USD'}}return {amount:m[1],currency:m[2].toUpperCase()}}));
const currencySchema=z.object({date:z.string().refine(v=>!Number.isNaN(Date.parse(v))).transform(v=>new Date(v).toISOString().slice(0,10)),base:code,rates:z.record(z.string().regex(/^[A-Z0-9.$_-]{1,30}$/),money.refine(v=>Number(v)>0))});
Decimal.set({precision:40,rounding:Decimal.ROUND_HALF_EVEN});
@Component({selector:'app-root',imports:[FormsModule, LiveRatesChartComponent],templateUrl:'./app.component.html',styleUrl:'./app.component.css'})
export class AppComponent{
 language=signal<Lang>(this.detectLang()); theme=signal<Theme>(this.detectTheme()); apiKey='';showKey=false;loading=signal(false);error=signal<string|null>(null);data=signal<Data|null>(null);private request?:AbortController;
 totals=computed(()=>{const d=this.data();if(!d)return[];const map=new Map<string,Decimal>();const add=(a:string,c:string)=>map.set(c,(map.get(c)??new Decimal(0)).plus(a));d.financeResult[0].transactions.forEach(x=>x.type==='paid'&&add(x.amount,x.currency));d.financeResult[1].forEach(x=>add(x.amount,x.currency));return [...map].map(([currency,value])=>({currency,amount:value.toString()})).sort((a,b)=>a.currency.localeCompare(b.currency))});
 total=computed(()=>{const d=this.data();if(!d)return'';const cv=(a:string,c:string)=>c===d.currencyData.base?new Decimal(a):new Decimal(a).dividedBy(d.currencyData.rates[c]);let sum=new Decimal(0);d.financeResult[0].transactions.forEach(x=>{if(x.type==='paid')sum=sum.plus(cv(x.amount,x.currency))});d.financeResult[1].forEach(x=>sum=sum.plus(cv(x.amount,x.currency)));const digits=new Intl.NumberFormat('en',{style:'currency',currency:d.currencyData.base}).resolvedOptions().maximumFractionDigits;return sum.toDecimalPlaces(digits,Decimal.ROUND_HALF_EVEN).toFixed(digits)});
 constructor(){this.applyTheme()}
 t(k:Key,v:Record<string,string>={}){return Object.entries(v).reduce((s,[a,b])=>s.replace(`{${a}}`,b),tr[this.language()][k] as string)}
 setLang(v:string){const l=v as Lang;this.language.set(l);localStorage.setItem('language',l);document.documentElement.lang=l}
 toggleTheme(){this.theme.update(v=>v==='light'?'dark':'light');this.applyTheme()}
 locale(){return ({en:'en-US',ru:'ru-RU',uk:'uk-UA'} as const)[this.language()]}
 currency(amount:string,currency:string){return new Intl.NumberFormat(this.locale(),{style:'currency',currency}).format(Number(amount))}
 rate(currency:string){const d=this.data()!;return currency===d.currencyData.base?'1':d.currencyData.rates[currency]}
 date(){return new Intl.DateTimeFormat(this.locale(),{dateStyle:'medium',timeZone:'UTC'}).format(new Date(`${this.data()!.currencyData.date}T00:00:00Z`))}
 async submit(){const key=this.apiKey.trim();if(!key){this.error.set(this.t('apiKeyRequired'));return}this.request?.abort();this.request=new AbortController();this.error.set(null);this.data.set(null);this.loading.set(true);try{this.data.set(await this.load(key,this.request.signal))}catch(e){if(this.request.signal.aborted)return;const x=e instanceof AppError?e:new AppError('unknownError');this.error.set(this.t(x.code,x.values))}finally{this.loading.set(false)}}
 private async load(key:string,signal:AbortSignal):Promise<Data>{if(!environment.currencyApiKey)throw new AppError('missingCurrencyApiKey');const [a,b,c]=await Promise.all([this.get('https://cpa-server-vtel.onrender.com/api/finance1',firstSchema,'Finance 1',signal,key),this.get('https://cpa-server-vtel.onrender.com/api/finance2',secondSchema,'Finance 2',signal,key),this.get(`https://api.currencyfreaks.com/v2.0/rates/latest?apikey=${encodeURIComponent(environment.currencyApiKey)}`,currencySchema,'CurrencyFreaks',signal)]);const available=new Set([c.base,...Object.keys(c.rates)]);const used=[...a.transactions.filter(x=>x.type==='paid').map(x=>x.currency),...b.map(x=>x.currency)];const missing=used.find(x=>!available.has(x));if(missing)throw new AppError('missingCurrencyRate',{currency:missing});return{financeResult:[a,b],currencyData:c}}
 private async get<T>(url:string,schema:z.ZodType<T>,source:string,signal:AbortSignal,key?:string){const headers:Record<string,string>={Accept:'application/json'};if(key)headers['x-api-key']=key;const r=await fetch(url,{headers,signal});const body:unknown=await r.json().catch(()=>null);if(!r.ok)throw new AppError('requestFailed',{source,status:String(r.status)});const parsed=schema.safeParse(body);if(!parsed.success)throw new AppError('invalidApiResponse',{source});return parsed.data}
 private detectLang():Lang{const saved=localStorage.getItem('language');if(saved==='en'||saved==='ru'||saved==='uk')return saved;for(const x of navigator.languages){const l=x.split('-')[0] as Lang;if(['en','ru','uk'].includes(l))return l}return'en'}
 private detectTheme():Theme{const saved=localStorage.getItem('theme');return saved==='light'||saved==='dark'?saved:matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
 private applyTheme(){document.documentElement.setAttribute('data-bs-theme',this.theme());localStorage.setItem('theme',this.theme())}
}


